server.port=8083

spring.datasource.url=jdbc:h2:file:./data/locationdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

url.weather=http://localhost:8082/weather